1. Write a Python Program to Add Two Matrices?

__Ans:-__

In [1]:
import numpy as np
def add_matrix(mat1, mat2):
    if (len(mat1), len(mat1[0])) == (len(mat2), len(mat2[0])):
        return(np.add(mat1, mat2))
    else:
        return 'Matrix addition not possible'

print(add_matrix([[1,2,3],[4,5,6]], [[1,2,7],[9,10,23]]))

[[ 2  4 10]
 [13 15 29]]


***

2. Write a Python Program to Multiply Two Matrices?

__Ans:-__

In [2]:
import numpy as np

def mul_matrix(mat1, mat2):
    try:
        return np.dot(mat1, mat2)
    except Exception as e:
        return e
print(mul_matrix([[1,2,3],[4,5,6]], [[1,2],[9,10],[4,5]]))

[[31 37]
 [73 88]]


***

3. Write a Python Program to Transpose a Matrix?

__Ans:-__

In [3]:
import numpy as np

def transpose(mat):
    return np.transpose(mat)
print(transpose([[1,2,3],[4,5,6]]))

[[1 4]
 [2 5]
 [3 6]]


***

4. Write a Python Program to Sort Words in Alphabetic Order?

__Ans:-__

In [4]:
def sort_words(arr):
    return sorted(arr)
print(sort_words(['Shreyas','Parab','Have','Enrolled','In','Full Stack Data Science']))

['Enrolled', 'Full Stack Data Science', 'Have', 'In', 'Parab', 'Shreyas']


***

5. Write a Python Program to Remove Punctuation From a String?

__Ans:-__


In [5]:
import re
def remove_punc(string):
    res = re.sub(r'\W',' ',string)
    return res
remove_punc('Gfg, is best : for ! Geeks ;')

'Gfg  is best   for   Geeks  '